from .brand_views import brand_router
from .margin_views import margin_router
from .catalog_views import catalog_router
from .auth_views import auth_router
from .employee_views import employee_router
from .shop_views import shop_router
from .supplier_views import supplier_router
from .new_arrival_views import arrive_router
from .actual_product_views import act_product_router
